### ISSUE TITLE
Core Data Multithreading Violations 

### ISSUE THREAD

**Issue by toto** [at-internet/atinternet-ios-swift-sdk#5] opened 2016-04-27 16:23 UTC
## Description

The SDK violates the Core Data Multithreading contract which can lead to crashes. 

This is AFAICT happens when calling any instance method of the `Storage` class without using the `performBlock()` method on the managed object context which happens if you do not use the SDK from the main thread. Since this is a tracking SDK non-main-thread usage should be the norm, not the exception.

Generally the managed object context of the `Storage` class is in `.MainQueueConcurrencyType` which is completely inappropriate for a tracking framework especially since the whole API is async. This type should only be used for UI work, which the SDK does not do.

Take a look at the core data concurrency documentation, this is really, really, really bad for a SDK. Esp. since it makes debugging your own core data driven app basically impossible. 
## Steps to reproduce
1. Integrate the SDK into your app
2. Launch the app with `-com.apple.CoreData.ConcurrencyDebug 1` as a launch argument (set in the schemes)
3. Watch the exceptions 
## Expected Result

No multithreading violations
## Workaround

Call any and all methods of the SDK only from the main queue/thread.

**Comment by d-theo** [comment] 2016-04-28 07:43
Hi, we are aware of the problem and are currently working on it. The problem is that the SDK performs tracking but also has a small part of UI (the debugger feature), that's why we are still with `.MainQueueConcurrencyType.`
The `performBlock` fix is in progress and will be released soon.

**Comment by d-theo** [comment] 2016-05-04 07:05
The new release 09cf221c94d057f6f51d3b50e63834f3f9ef0f8f should fix the issue

**Closed as completed by d-theo** 2016-05-04 07:05 UTC
